language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - 3.6
env:
  - DJANGO=1.4
  - DJANGO=1.5
  - DJANGO=1.6
  - DJANGO=1.7
  - DJANGO=1.8
  - DJANGO=1.9
  - DJANGO=1.10
  - DJANGO=1.11
  - DJANGO=2.0
matrix:
  exclude:
    # Python/Django combinations that aren't officially supported
    # Django 1.4/1.5 don't support Python 3
    - { python: 3.2, env: DJANGO=1.4 }
    - { python: 3.3, env: DJANGO=1.4 }
    - { python: 3.4, env: DJANGO=1.4 }
    - { python: 3.5, env: DJANGO=1.4 }
    - { python: 3.6, env: DJANGO=1.4 }
    - { python: 3.2, env: DJANGO=1.5 }
    - { python: 3.3, env: DJANGO=1.5 }
    - { python: 3.4, env: DJANGO=1.5 }
    - { python: 3.5, env: DJANGO=1.5 }
    - { python: 3.6, env: DJANGO=1.5 }
    # Django 1.6 does not support 3.4-3.6
    - { python: 3.4, env: DJANGO=1.6 }
    - { python: 3.5, env: DJANGO=1.6 }
    - { python: 3.6, env: DJANGO=1.6 }
    # Django 1.7 does not support 2.6, 3.5-3.6
    - { python: 2.6, env: DJANGO=1.7 }
    - { python: 3.5, env: DJANGO=1.7 }
    - { python: 3.6, env: DJANGO=1.7 }
    # Django 1.8 does not support 2.6, 3.6
    - { python: 2.6, env: DJANGO=1.8 }
    - { python: 3.6, env: DJANGO=1.8 }
    # Django 1.9/1.10 do not support 2.6, 3.2-3.3, 3.6
    - { python: 2.6, env: DJANGO=1.9 }
    - { python: 3.2, env: DJANGO=1.9 }
    - { python: 3.3, env: DJANGO=1.9 }
    - { python: 3.6, env: DJANGO=1.9 }
    - { python: 2.6, env: DJANGO=1.10 }
    - { python: 3.2, env: DJANGO=1.10 }
    - { python: 3.3, env: DJANGO=1.10 }
    - { python: 3.6, env: DJANGO=1.10 }
    # Django 1.11 does not support 2.6, 3.2-3.3
    - { python: 2.6, env: DJANGO=1.11 }
    - { python: 3.2, env: DJANGO=1.11 }
    - { python: 3.3, env: DJANGO=1.11 }
    # Django 2.0 does not support Python 2, 3.2-3.3
    - { python: 2.6, env: DJANGO=2.0 }
    - { python: 2.7, env: DJANGO=2.0 }
    - { python: 3.2, env: DJANGO=2.0 }
    - { python: 3.3, env: DJANGO=2.0 }
  include:
    - { python: 2.7, env: TOXENV=py27-flake8 }
    - { python: 2.7, env: TOXENV=py27-pylint }
    - { python: 3.6, env: TOXENV=py36-flake8 }
    - { python: 3.6, env: TOXENV=py36-pylint }
install:
  - pip install "virtualenv<14.0.0" tox-travis
script: python setup.py test
